"""
As of CompensateColors version ###
'Select where to perform color compensation': 'Within objects' or 'Across entire image'
'Select an object to perform compensation within': 'Foci'
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No' or 'Yes'
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No' or 'Yes, per image' or 'Yes, per group'
'Should histogram matching be performed between the image groups?': 'No' or 'Yes, pre-masking or on unmasked images' or 'Yes, post-masking to objects'
'What compensation class should serve as the template histogram?': 1 or 2 or 3 or 4
'Should images be rescaled 0-1 after compensating?': 'No' or 'Yes'
'Should the images be divided by a scalar based on group percentiles': 'No' or 'Yes'
'What percentile should be used for multiplication': 0 > any number > 100, recommended 99 or 99.5 or 99.9
'Should the images have a tophat filter applied before correction?': 'No' or 'Yes'
'What size radius should be used for the tophat filter?': any number, recommended
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No' or 'Yes'
'What size radius should be used for the LoG filter?': any number, recommended 1 or 2
'Should the images have a Difference of Gaussians filter applied before correction?': 'No' or 'Yes'
'What size sigma should be used for the DoG low sigma?': any number, recommended #
'What size radius should be used for the DoG low sigma?': any number, recommended #
"""
Percent99 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'No',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'Yes',
'What percentile should be used for multiplication': 99,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

Percent999 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'No',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'Yes',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

Percent999Rescale = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'No',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'Yes',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

Percent999RescaleLog1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'No',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'Yes',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistARescale = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistCRescale = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 2,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistGRescale = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 3,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistTRescale = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 4,
'Should images be rescaled 0-1 after compensating?': 'Yes',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistALog1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistALog2 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 2,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistALog3 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 1,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 3,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistCLog1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 2,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistGLog1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 3,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistTLog1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 4,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'No',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'Yes',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistTTop1 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 4,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'Yes',
'What size radius should be used for the tophat filter?': 1,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistTTop3 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 4,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'Yes',
'What size radius should be used for the tophat filter?': 3,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}

MaskHistTTop6 = {'Select where to perform color compensation': 'Within objects',
'Select an object to perform compensation within': 'Foci',
'Should individual images be rescaled 0-1 before compensating pre-masking or on unmasked images?': 'No',
'Should images be rescaled 0-1 before compensating but after masking to objects?': 'No',
'Should histogram matching be performed between the image groups?': 'Yes, post-masking to objects',
'What compensation class should serve as the template histogram?': 4,
'Should images be rescaled 0-1 after compensating?': 'No',
'Should the images be divided by a scalar based on group percentiles': 'No',
'What percentile should be used for multiplication': 99.9,
'Should the images have a tophat filter applied before correction?': 'Yes',
'What size radius should be used for the tophat filter?': 6,
'Should the images have a Laplacian of Gaussian filter applied before correction?': 'No',
'What size radius should be used for the LoG filter?': 1,
'Should the images have a Difference of Gaussians filter applied before correction?': 'No',
'What size sigma should be used for the DoG low sigma?': 1,
'What size radius should be used for the DoG low sigma?': 1}
